-- [[ 🟢 CHRISSHUB V2 SUPREME - V3 FINAL STABLE 🟢 ]]
-- [[ DEVELOPER: SASWARE32 | TIKTOK: @sasware32 ]]
-- [[ ESP FIX: NO AUTO-CLEAN | AIMBOT: STICKY | NOCLIP: FULL ]]

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local CoreGui = game:GetService("CoreGui")
local lp = Players.LocalPlayer
local camera = workspace.CurrentCamera

-- [[ 🔑 BASE DE DATOS: 15 KEYS ]]
local CH_KEYS = {
    "CHKEY_2964173850", "CHKEY_8317642950", "CHKEY_5729184630", "CHKEY_9463825170",
        "CHKEY_1857396240", "CHKEY_7248163950", "CHKEY_3692581740", "CHKEY_6159274830",
            "CHKEY_4836917250", "CHKEY_8527419630", "CHKEY_2769318450", "CHKEY_9148526730",
                "CHKEY_5382761940", "CHKEY_7615928340", "CHKEY_3974182650"
                }

                local Config = {
                    Toggles = {
                            Noclip = false, InfJump = false, WalkSpeed = false,
                                    Aimbot = false, KillAura = false,
                                            ESP_Murd = false, ESP_Sheriff = false, ESP_Inno = false, Traces = false
                                                },
                                                    SpeedValue = 50
                                                    }

                                                    -- [[ 📢 SISTEMA DE NOTIFICACIONES RECTANGULARES ]]
                                                    local function SendNotify(txt, col)
                                                        spawn(function()
                                                                local sg = Instance.new("ScreenGui", CoreGui)
                                                                        local frame = Instance.new("Frame", sg)
                                                                                frame.Size = UDim2.new(0, 240, 0, 50)
                                                                                        frame.Position = UDim2.new(1, 10, 0.15, 0)
                                                                                                frame.BackgroundColor3 = Color3.fromRGB(5, 5, 10)
                                                                                                        Instance.new("UICorner", frame)
                                                                                                                local st = Instance.new("UIStroke", frame); st.Color = col; st.Thickness = 2
                                                                                                                        
                                                                                                                                local l = Instance.new("TextLabel", frame)
                                                                                                                                        l.Size = UDim2.new(1, 0, 1, 0); l.Text = txt; l.TextColor3 = col
                                                                                                                                                l.Font = Enum.Font.GothamBold; l.BackgroundTransparency = 1; l.TextSize = 13
                                                                                                                                                        
                                                                                                                                                                frame:TweenPosition(UDim2.new(1, -250, 0.15, 0), "Out", "Back", 0.5, true)
                                                                                                                                                                        task.wait(3.5)
                                                                                                                                                                                frame:TweenPosition(UDim2.new(1, 10, 0.15, 0), "In", "Quad", 0.5, true)
                                                                                                                                                                                        task.wait(0.6); sg:Destroy()
                                                                                                                                                                                            end)
                                                                                                                                                                                            end

                                                                                                                                                                                            -- [[ 👁️ MOTOR ESP (CORREGIDO: DETECTA JUGADORES NUEVOS, NO BORRA) ]]
                                                                                                                                                                                            local active_esp = {}

                                                                                                                                                                                            local function GetRole(p)
                                                                                                                                                                                                if not p or not p.Character then return "Innocent" end
                                                                                                                                                                                                    if p.Character:FindFirstChild("Knife") or p.Backpack:FindFirstChild("Knife") then return "Murderer" end
                                                                                                                                                                                                        if p.Character:FindFirstChild("Gun") or p.Backpack:FindFirstChild("Gun") then return "Sheriff" end
                                                                                                                                                                                                            return "Innocent"
                                                                                                                                                                                                            end

                                                                                                                                                                                                            local function CreateESP(p)
                                                                                                                                                                                                                if active_esp[p] then return end -- Si ya tiene ESP, no crear otro

                                                                                                                                                                                                                    local highlight = Instance.new("Highlight", CoreGui)
                                                                                                                                                                                                                        highlight.OutlineTransparency = 0
                                                                                                                                                                                                                            highlight.FillTransparency = 0.4
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                    local line = Drawing.new("Line")
                                                                                                                                                                                                                                        line.Thickness = 2
                                                                                                                                                                                                                                            line.Transparency = 1
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    active_esp[p] = {Highlight = highlight, Line = line}
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            local connection
                                                                                                                                                                                                                                                                connection = RunService.RenderStepped:Connect(function()
                                                                                                                                                                                                                                                                        if p.Character and p.Character:FindFirstChild("HumanoidRootPart") and p.Character:FindFirstChild("Humanoid") then
                                                                                                                                                                                                                                                                                    local role = GetRole(p)
                                                                                                                                                                                                                                                                                                local color = (role == "Murderer" and Color3.new(1,0,0)) or (role == "Sheriff" and Color3.new(0,0.7,1)) or Color3.new(0,1,0)
                                                                                                                                                                                                                                                                                                            local enabled = (role == "Murderer" and Config.Toggles.ESP_Murd) or (role == "Sheriff" and Config.Toggles.ESP_Sheriff) or (role == "Innocent" and Config.Toggles.ESP_Inno)
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                    -- El ESP solo se apaga si la opción está desactivada o el jugador murió
                                                                                                                                                                                                                                                                                                                                                if enabled and p.Character.Humanoid.Health > 0 then
                                                                                                                                                                                                                                                                                                                                                                highlight.Enabled = true
                                                                                                                                                                                                                                                                                                                                                                                highlight.Adornee = p.Character
                                                                                                                                                                                                                                                                                                                                                                                                highlight.FillColor = color
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                local pos, vis = camera:WorldToViewportPoint(p.Character.HumanoidRootPart.Position)
                                                                                                                                                                                                                                                                                                                                                                                                                                                if Config.Toggles.Traces and vis then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line.Visible = true; line.Color = color
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line.From = Vector2.new(camera.ViewportSize.X/2, camera.ViewportSize.Y)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            line.To = Vector2.new(pos.X, pos.Y)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else line.Visible = false end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        highlight.Enabled = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line.Visible = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end
                                                                                                        
